#!/usr/bin/env python3
"""Render src/data/reviews.json into src/partials/reviews.html.

    python3 tools/build-reviews.py && python3 tools/build.py

Same shape as build-team.py: data in, partial out, committed so the site can be
built without network access or an API key.

If there is no review data yet, this writes the EmbedSocial widget instead —
the homepage keeps working exactly as it does today, and swaps to our own feed
the moment `fetch-reviews.py` has something to give it. Nothing is invented to
fill the gap: every review on the page is one a real person left on Google.
"""
from __future__ import annotations

import html
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DATA = ROOT / "src" / "data" / "reviews.json"
OUT = ROOT / "src" / "partials" / "reviews.html"

# How many to show. Google caps us at five per place, so with three studios
# twelve fills four rows of three on desktop with a little in reserve.
LIMIT = 12

STAR = ('<svg viewBox="0 0 20 19" aria-hidden="true"{cls}>'
        '<path d="M10 0l2.6 6.3 6.8.5-5.2 4.4 1.6 6.6L10 14.2 4.2 17.8l1.6-6.6L.6 6.8l6.8-.5z"/>'
        '</svg>')

GOOGLE_G = (
    '<svg viewBox="0 0 24 24" aria-hidden="true">'
    '<path fill="#4285F4" d="M23.5 12.3c0-.8-.1-1.6-.2-2.3H12v4.5h6.4a5.5 5.5 0 0 1-2.4 3.6v3h3.9c2.3-2.1 3.6-5.2 3.6-8.8z"/>'
    '<path fill="#34A853" d="M12 24c3.2 0 6-1.1 8-2.9l-3.9-3a7.2 7.2 0 0 1-10.7-3.8h-4v3.1A12 12 0 0 0 12 24z"/>'
    '<path fill="#FBBC05" d="M5.3 14.3a7.1 7.1 0 0 1 0-4.6v-3.1h-4a12 12 0 0 0 0 10.8z"/>'
    '<path fill="#EA4335" d="M12 4.8c1.8 0 3.4.6 4.6 1.8l3.5-3.5A12 12 0 0 0 1.3 6.6l4 3.1A7.2 7.2 0 0 1 12 4.8z"/>'
    '</svg>'
)

FALLBACK = '''<!-- Generated by tools/build-reviews.py — do not edit by hand.

     There is no review data in src/data/reviews.json yet, so this falls back
     to the EmbedSocial widget the site launched with. Run

         export GOOGLE_MAPS_API_KEY=...
         python3 tools/fetch-reviews.py
         python3 tools/build-reviews.py && python3 tools/build.py

     to replace it with our own branded feed. Nothing here is placeholder
     copy — no review is shown until a real one has been fetched. -->
<div class="embedsocial-hashtag" data-ref="fb980bf40d0a2b8e8a2cb383d5e0eff865a98305" data-embedsocial></div>
'''


def stars(n: int, big: bool = False) -> str:
    n = int(round(n or 0))
    body = "".join(
        STAR.format(cls="" if i < n else ' class="is-empty"') for i in range(5)
    )
    return f'<span class="stars{" stars--lg" if big else ""}" aria-hidden="true">{body}</span>'


def card(r: dict) -> str:
    return f'''      <li class="rv-card">
        {stars(r.get("rating", 5))}
        <p class="rv-card__text">{html.escape(r.get("text", ""))}</p>
        <div class="rv-card__who">
          <span class="rv-card__name">{html.escape(r.get("author", "Anonymous"))}</span>
          <span class="rv-card__when">{html.escape(r.get("when", ""))}</span>
        </div>
        <span class="rv-card__where">{html.escape(r.get("studio", ""))}</span>
      </li>'''


def main() -> int:
    if not DATA.exists():
        OUT.write_text(FALLBACK)
        print(f"  no {DATA.relative_to(ROOT)} — wrote the EmbedSocial fallback")
        return 0

    data = json.loads(DATA.read_text())
    reviews = data.get("reviews", [])
    if not reviews:
        OUT.write_text(FALLBACK)
        print("  reviews.json has no reviews — wrote the EmbedSocial fallback")
        return 0

    shown = reviews[:LIMIT]
    overall = data.get("overall")
    total = data.get("total") or 0

    head = f'''  <div class="rv-head">
    <div class="rv-score">
      <span class="rv-score__n">{overall if overall else ""}</span>
      <span class="rv-score__of">out of 5</span>
    </div>
    <div class="rv-meta">
      {stars(overall or 5, big=True)}
      <span class="rv-src">{GOOGLE_G} {total:,} Google reviews &middot; all three studios</span>
    </div>
  </div>
'''

    OUT.write_text(
        "<!-- Generated by tools/build-reviews.py from src/data/reviews.json.\n"
        "     Do not edit by hand — re-run the fetcher instead. Every review below\n"
        "     is one a real person left on Google. -->\n"
        + head
        + '  <ul class="rv-grid">\n'
        + "\n".join(card(r) for r in shown)
        + "\n  </ul>\n"
    )
    print(f"  {len(shown)} review(s) rendered, {overall} across {total:,} ratings")
    print(f"  wrote {OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
