#!/usr/bin/env python3
"""Generate the Journal listings from the posts themselves.

    python3 tools/build-blog-index.py && python3 tools/build.py

Writes one partial per listing into src/partials/:

    posts-all.html    every post          -> included by /blog
    posts-news.html   posts tagged News   -> included by /blog/news

Before this, the listing on /blog was hand-written. That works until a post is
added and the listing is not updated, or a title is edited in one place and not
the other — and it made a second, filtered listing a second thing to keep in
sync by hand. Now both come from the posts' own front matter, so a new post
appears in every listing it belongs in the moment it is built.

The card fields (excerpt, read_time, card, card_w, card_h) live in each post's
front matter alongside title and date.
"""
from __future__ import annotations

import html
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
PAGES = ROOT / "src" / "pages"
PARTIALS = ROOT / "src" / "partials"

MONTHS = ("January", "February", "March", "April", "May", "June", "July",
          "August", "September", "October", "November", "December")

# listing name -> (category filter, "" for everything)
LISTINGS = {"all": "", "news": "News"}


def front_matter(text: str) -> dict[str, str]:
    m = re.match(r"<!--\s*\n(.*?)\n-->", text, re.S)
    if not m:
        return {}
    meta = {}
    for line in m.group(1).splitlines():
        if ":" in line:
            k, _, v = line.partition(":")
            meta[k.strip()] = v.strip()
    return meta


def posts() -> list[dict]:
    out = []
    for f in PAGES.glob("blog-*.html"):
        meta = front_matter(f.read_text())
        if not meta.get("published") or not meta.get("path"):
            continue
        meta["cats"] = [c.strip() for c in meta.get("category", "").split(",") if c.strip()]
        out.append(meta)
    # newest first
    out.sort(key=lambda m: m.get("published", ""), reverse=True)
    return out


def pretty(iso: str) -> str:
    try:
        y, m, d = (int(x) for x in iso.split("-"))
        return f"{MONTHS[m - 1]} {d}, {y}"
    except Exception:                                            # noqa: BLE001
        return iso


def cats(post: dict) -> str:
    return "".join(
        f'<span class="badge badge--outline">{html.escape(c)}</span>' for c in post["cats"]
    )


def meta_line(post: dict) -> str:
    bits = [pretty(post["published"])]
    if post.get("read_time"):
        bits.append(post["read_time"])
    return " &middot; ".join(bits)


def lead(post: dict) -> str:
    return f'''    <article class="post-lead">
      <div class="post-lead__media"><img src="{post.get("card", "")}" alt="" width="{post.get("card_w", 900)}" height="{post.get("card_h", 600)}"></div>
      <div class="post-lead__body">
        <div class="post-card__cats">{cats(post)}</div>
        <h2 class="post-lead__title"><a href="{post["path"]}">{post.get("headline") or post["title"]}</a></h2>
        <p class="post-lead__excerpt">{post.get("excerpt", "")}</p>
        <div class="post-card__meta">{meta_line(post)}</div>
      </div>
    </article>
'''


def card(post: dict) -> str:
    return f'''      <li class="post-card">
        <div class="post-card__media"><img src="{post.get("card", "")}" alt="" width="{post.get("card_w", 900)}" height="{post.get("card_h", 600)}" loading="lazy"></div>
        <div class="post-card__cats">{cats(post)}</div>
        <h3 class="post-card__title"><a href="{post["path"]}">{post.get("headline") or post["title"]}</a></h3>
        <p class="post-card__excerpt">{post.get("excerpt", "")}</p>
        <div class="post-card__meta">{meta_line(post)}</div>
      </li>'''


def main() -> int:
    everything = posts()
    if not everything:
        raise SystemExit("no posts with a published date — nothing to list")

    for name, want in LISTINGS.items():
        chosen = [p for p in everything if not want or want in p["cats"]]
        if not chosen:
            print(f"  {name}: no posts match {want!r} — skipped")
            continue
        body = ("<!-- Generated by tools/build-blog-index.py from the posts'\n"
                "     own front matter. Do not edit by hand — edit the post. -->\n"
                + lead(chosen[0])
                + '    <ul class="posts">\n'
                + "\n".join(card(p) for p in chosen[1:])
                + "\n    </ul>\n")
        out = PARTIALS / f"posts-{name}.html"
        out.write_text(body)
        print(f"  {name:<5} {len(chosen)} post(s) -> {out.relative_to(ROOT)}")

    print("  next: python3 tools/build.py")
    return 0


if __name__ == "__main__":
    sys.exit(main())
